Feature/tg 88 programs delete
JU-DEV-LatamBootcamp/Klockan-Frontend pull request #18
Opened 2024-02-03 21:50 UTC by carlos-canedo-dev

Implementation of programs delete functionality and Update of dialog components

2024-02-03 23:59 UTC, AndresJavierNazzari commented
We should use PR Template
https://github.com/JU-DEV-LatamBootcamp/Klockan-Backend/blob/develop/.github/pull_request_template.md
Providing some images as evidence

2024-02-04 00:18 UTC, AndresJavierNazzari requested changes
We should use PR Template
https://github.com/JU-DEV-LatamBootcamp/Klockan-Backend/blob/develop/.github/pull_request_template.md
Providing some images as evidence

Yoy can see an example here:
https://github.com/JU-DEV-LatamBootcamp/Klockan-Frontend/pull/15

2024-02-05 09:09 UTC, AndresJavierNazzari approved these changes

2024-02-05 14:14 UTC, carlosBarriosCarvajal approved these changes

2024-02-05 14:18 UTC, merged